# Generated by Django 5.0.2 on 2024-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_title_expectedgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='court',
            field=models.CharField(choices=[('ЛИДЕР', 'ЛИДЕР (Суходольский м-н, Восточный округ, Тюмень) '), ('Sofi-land', 'Sofi-land (Лесобазовская 8а/1 Тура м-н, Ленинский округ, Тюмень) ')], default='Court A', max_length=20, verbose_name='Корт'),
        ),
    ]
